### ISSUE TITLE
import qnorm fails on python 3.5

### ISSUE THREAD

**Issue by mheskett** [Maarten-vd-Sande/qnorm#5]
* qnorm version:qnorm-0.6.2
* Python version:3.5
* Operating System: mac os 

### Description
Tried to import qnorm.

Traceback (most recent call last):
  File "myfile.py", line 16, in <module>
    import qnorm
  File "//anaconda/lib/python3.5/site-packages/qnorm/__init__.py", line 2, in <module>
    from .quantile_normalize import quantile_normalize
  File "//anaconda/lib/python3.5/site-packages/qnorm/quantile_normalize.py", line 76
    f"quantile_normalize not implemented for type {type(data)}"
                                                              ^
SyntaxError: invalid syntax

**Comment by Maarten-vd-Sande** [comment]
@mheskett thanks for the issue. Somehow I did not notice it, sorry for the late reply!

Indeed, qnorm does not work with python versions lower than 3.6. How did you install qnorm? From Anaconda, pypi (pip) or source (this github repo)? I _thought_ it would give a warning/error when installing it from the wrong python version, but obviously it doesn't. If I know where it goes wrong I can solve it :)
